jobs:
    main:
        image: node:6
        steps:
            - install: npm install
            - test: npm test
            - publish: ./ci/publish
        secrets:
            - NPM_TOKEN
            - GIT_TOKEN
            - DOCKER_TRIGGER
