apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sdapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: screwdriver
        tier: api
    spec:
      containers:
      - name: screwdriver-api
        image: screwdrivercd/screwdriver
        ports:
        - containerPort: 8080
        # Environment variables that point to your secrets in your secrets.yaml
        env:
          - name: DATASTORE_PLUGIN
            value: dynamodb
          - name: HOST
            value: 0.0.0.0
          - name: API_URI
            value: http://a4677c9873c9611e6aa7102b92f75d5c-1135862614.us-west-2.elb.amazonaws.com
          - name: DATA_DIR
            value: /opt/screwdriver/data
          - name: SECRET_JWT_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: secrets
                key: jwtprivatekey
          - name: SECRET_OAUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: secrets
                key: oauthclientid
          - name: SECRET_OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: secrets
                key: oauthclientsecret
          - name: SECRET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets
                key: password
          - name: K8S_TOKEN
            valueFrom:
              secretKeyRef:
                name: default-token-sw0ar     # insert your Kubernetes <DEFAULT_TOKEN_NAME> here
                key: token
          - name: DATASTORE_DYNAMODB_ID
            valueFrom:
              secretKeyRef:
                name: secrets
                key: dynamodbid
          - name: DATASTORE_DYNAMODB_SECRET
            valueFrom:
              secretKeyRef:
                name: secrets
                key: dynamodbsecret
