apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sdapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: screwdriver
        tier: api
    spec:
      containers:
      - name: screwdriver-api
        image: screwdrivercd/api
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: apikey
          mountPath: /etc/kubernetes/apikey
          readOnly: true
        - name: screwdriver-imdb
          mountPath: /opt/screwdriver/data
        env:
          - name: DATA_DIR
            value: /opt/screwdriver/data
          - name: SECRET_JWT_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: plugin-login-secrets
                key: jwtprivatekey
          - name: SECRET_OAUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: plugin-login-secrets
                key: oauthclientid
          - name: SECRET_OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: plugin-login-secrets
                key: oauthclientsecret
          - name: SECRET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: plugin-login-secrets
                key: password
          - name: K8S_TOKEN
            valueFrom:
              secretKeyRef:
                name: default-token-sw0ar
                key: token

      volumes:
      - name: screwdriver-imdb
        awsElasticBlockStore:
          volumeID: vol-4e36cdc7
          fsType: ext4
